// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Diagnostic message families and their semantic base codes. Context refines
//! ambiguous families; this table never reads a fixture path or source identity.

pub(super) const RULES: &[(&str, &str, u32)] = &[
    ("BTS1000", "expected `{}`", 1005),
    ("BTS1000", "expected a type", 1110),
    ("BTS1000", "`{}` is not a valid private name", 18012),
    ("BTS1000", "a getter cannot have parameters", 1054),
    ("BTS1000", "a parameter property cannot be a rest parameter or a binding pattern", 1187),
    ("BTS1000", "a setter cannot have a return type annotation", 1095),
    ("BTS1000", "a setter must have exactly one parameter", 1049),
    ("BTS1000", "a setter parameter cannot be a rest, optional, defaulted or destructured parameter", 1051),
    ("BTS1000", "an accessibility modifier cannot be used with a private identifier", 18010),
    ("BTS1000", "decorators are not valid here; they decorate a class or a class member", 1206),
    ("BTS1000", "expected an interface field name", 1131),
    ("BTS1000", "initializers are not allowed in ambient contexts", 1039),
    ("BTS1000", "parameter modifiers must be an accessibility modifier, then `{}`, each at most once", 1029),
    ("BTS1000", "the closing JSX tag does not match the opening tag", 17002),
    ("BTS1000", "unexpected `{}` in JSX text; use `{}`", 1382),
    ("BTS1000", "unterminated JSX element", 17008),
    ("BTS2000", "cannot resolve `{}` from `{}`: {}", 2792),
    ("BTS2002", "a decorator can only decorate a method implementation, not an overload", 1249),
    ("BTS2002", "decorators are not valid here: they decorate a class or a class member", 1206),
    ("BTS2002", "decorators are not valid on parameters unless `{}` is enabled", 1206),
    ("BTS3000", "duplicate declaration of `{}`", 2300),
    ("BTS3000", "duplicate identifier `{}`", 2300),
    ("BTS3000", "duplicate implementation of class method `{}`", 2393),
    ("BTS3000", "multiple constructor implementations are not allowed", 2392),
    ("BTS3001", "`{}` has no value binding (type-only declaration or import)", 2693),
    ("BTS3001", "`{}` was imported with `{}` and cannot be used as a value", 1361),
    ("BTS3001", "cannot find name `{}`", 2304),
    ("BTS3001", "cannot find the JSX tag name `{}`", 2304),
    ("BTS3001", "cannot find the name `{}` that the JSX `{}` `{}` needs in scope", 2874),
    ("BTS3001", "module `{}` has no exported member `{}`", 2305),
    ("BTS3001", "private identifier `{}` is not declared by the enclosing class", 2339),
    ("BTS3001", "property `{}` does not exist on type `{}`", 2339),
    ("BTS3001", "unknown class heritage name {}", 2304),
    ("BTS3002", "cannot find type `{}`", 2304),
    ("BTS3002", "module `{}` has no exported type `{}`", 2459),
    ("BTS3002", "namespace `{}` has no exported member `{}`", 2694),
    ("BTS3003", "JSX element implicitly has type `{}` because no interface `{}` exists", 7026),
    ("BTS3003", "TS2540: cannot mutate readonly property `{}`", 2540),
    ("BTS3003", "TS7022: `{}` needs a type annotation because its initializer depends on a circular import", 7022),
    ("BTS3003", "`{}` can only be called in the constructor of a derived class, and `{}` has no base", 2335),
    ("BTS3003", "`{}` can only be referenced in a derived class, and `{}` has no base", 2335),
    ("BTS3003", "`{}` implicitly has an `{}` type", 2683),
    ("BTS3003", "`{}` is declared but never read", 6133),
    ("BTS3003", "`{}` is not a member of enum `{}`", 7015),
    ("BTS3003", "`{}` is only valid inside an async function", 18037),
    ("BTS3003", "`{}` must be called before `{}` is accessed in a derived constructor", 17009),
    ("BTS3003", "`{}` only refers to a type, but is being used as a value", 2708),
    ("BTS3003", "a `{}` call is only permitted in a constructor", 2337),
    ("BTS3003", "a computed enum member must be a number, not `{}`", 18033),
    ("BTS3003", "a const enum member initializer must be a constant expression", 2474),
    ("BTS3003", "a constructor overload signature cannot have a default initializer", 2371),
    ("BTS3003", "a decorator is called with {n} arguments (the value and its context) but this one requires {n}", 1238),
    ("BTS3003", "a getter must return a value", 2378),
    ("BTS3003", "a member of the const enum `{}` can only be accessed with a string literal", 2476),
    ("BTS3003", "a method overload signature cannot have a default initializer", 2371),
    ("BTS3003", "a rest parameter requires an array or tuple annotation", 2370),
    ("BTS3003", "accessor `{}` of type `{}` is not assignable to the base property type `{}`", 2416),
    ("BTS3003", "an index of type `{}` cannot be used on enum `{}`", 7053),
    ("BTS3003", "argument {n} has type `{}`, which is not assignable to method parameter `{}` of type `{}`", 2345),
    ("BTS3003", "argument {n} has type `{}`, which is not assignable to parameter `{}` of type `{}`", 2345),
    ("BTS3003", "assignment has type `{}`, which is not assignable to property `{}` of type `{}`", 2322),
    ("BTS3003", "attribute `{}` does not exist on the element's props (`{}`)", 2322),
    ("BTS3003", "attribute `{}` has type `{}`, which is not assignable to `{}`", 2322),
    ("BTS3003", "call argument {n} has an incompatible type", 2345),
    ("BTS3003", "cannot extend class `{}`: its constructor is private", 2675),
    ("BTS3003", "cannot mutate readonly property `{}`", 2540),
    ("BTS3003", "catch variable of type `{}` is not assignable to the declared type", 2322),
    ("BTS3003", "class `{}` cannot be used as a JSX component: its instance type is not a `{}`", 2786),
    ("BTS3003", "class `{}` incorrectly extends `{}`: types have separate declarations of the private property `{}`", 2415),
    ("BTS3003", "class defines `{}` as a property but the base class defines it as an accessor", 2610),
    ("BTS3003", "class defines `{}` as an accessor but the base class defines it as a method", 2416),
    ("BTS3003", "class defines `{}` as an accessor but the base class defines it as a property", 2611),
    ("BTS3003", "class field `{}` implicitly has an `{}` type", 7006),
    ("BTS3003", "class heritage {} is not a constructor", 2507),
    ("BTS3003", "class method `{}` is incompatible with inherited method from `{}`", 2416),
    ("BTS3003", "class method `{}` is not assignable to the inherited overload set of `{}`", 2416),
    ("BTS3003", "class {} cannot be called without `{}`", 2348),
    ("BTS3003", "class {} has a cyclic base expression", 2506),
    ("BTS3003", "constructor implementation is missing", 2390),
    ("BTS3003", "constructor of class {} is private and is not accessible here", 2673),
    ("BTS3003", "constructor of class {} is protected and is not accessible here", 2674),
    ("BTS3003", "constructor of derived class `{}` must contain a `{}` call", 2377),
    ("BTS3003", "constructor overload is incompatible with its implementation", 2394),
    ("BTS3003", "constructor overload requires an immediately following implementation", 2390),
    ("BTS3003", "default initializer has type `{}`, which is not assignable to parameter `{}` of type `{}`", 2322),
    ("BTS3003", "enum member `{}` must have an initializer", 1061),
    ("BTS3003", "enum member `{}` is used before its initialization", 2651),
    ("BTS3003", "fallthrough case in switch", 7029),
    ("BTS3003", "imported value `{}` has no construct signature", 2351),
    ("BTS3003", "in an enum with several declarations, only one may omit the initializer of its first member", 2432),
    ("BTS3003", "initializer has type `{}`, which is not assignable to `{}`", 2322),
    ("BTS3003", "invalid strict-mode binding `{}`", 1100),
    ("BTS3003", "method {} expects {n} to {n} argument(s), got {n}", 2554),
    ("BTS3003", "missing required props: {}", 2322),
    ("BTS3003", "namespace `{}` has no run-time members and cannot be used as a value", 2708),
    ("BTS3003", "namespace `{}` was imported with `{}` and cannot be used as a value", 1361),
    ("BTS3003", "no constructor of class {} accepts the `{}` call arguments", 2345),
    ("BTS3003", "no constructor of class {} accepts the supplied argument types", 2345),
    ("BTS3003", "no overload of function {} accepts the supplied argument types", 2769),
    ("BTS3003", "no overload of instance method {} matches the supplied argument types", 2769),
    ("BTS3003", "no overload of static method {} matches the supplied argument types", 2769),
    ("BTS3003", "overload signature for class method `{}` is incompatible with its implementation", 2394),
    ("BTS3003", "overload signature for class method `{}` requires an immediately following implementation", 2391),
    ("BTS3003", "overload signatures of `{}` must all be public, private or protected", 2385),
    ("BTS3003", "parameter `{}` implicitly has an `{}` type", 7006),
    ("BTS3003", "parameter `{}` is declared but never read", 6133),
    ("BTS3003", "private identifier `{}` does not exist on type `{}`", 2339),
    ("BTS3003", "property `{}` does not exist on type `{}`", 2339),
    ("BTS3003", "property `{}` has no initializer and is not definitely assigned in the constructor", 2564),
    ("BTS3003", "property `{}` is private and only accessible within class `{}`", 2341),
    ("BTS3003", "property `{}` is private in class `{}` but protected in the base class `{}`", 2415),
    ("BTS3003", "property `{}` is private in class `{}` but public in the base class `{}`", 2415),
    ("BTS3003", "property `{}` is protected and only accessible within class `{}`", 2445),
    ("BTS3003", "property `{}` is protected in class `{}` but public in the base class `{}`", 2415),
    ("BTS3003", "property `{}` is used before its initialization", 2729),
    ("BTS3003", "property `{}` of type `{}` is not assignable to the base property type `{}`", 2416),
    ("BTS3003", "property `{}` will overwrite the base property; add an initializer or remove the redundant declaration", 2612),
    ("BTS3003", "recursive return type inference requires a return annotation", 7023),
    ("BTS3003", "setter `{}` has an implicitly `{}` parameter", 7032),
    ("BTS3003", "spread attribute `{}` has type `{}`, which is not assignable to `{}`", 2322),
    ("BTS3003", "subsequent declarations of property `{}` must have the same type", 2717),
    ("BTS3003", "the const enum `{}` can only be used in a property or index access", 2475),
    ("BTS3003", "the element's children have type `{}`, which is not assignable to `{}`", 2322),
    ("BTS3003", "the getter and setter of `{}` must have the same accessibility", 2808),
    ("BTS3003", "this component's return type `{}` is not a valid JSX element", 2786),
    ("BTS3003", "this decorator accepts too few arguments to be used as a decorator; did you mean to call it first and write `{}`?", 1329),
    ("BTS3003", "this decorator expression has type `{}`, which is not callable", 1238),
    ("BTS3003", "this decorator returns `{}`, which a auto-accessor decorator cannot return", 1270),
    ("BTS3003", "this decorator returns `{}`, which a class {} cannot return", 1270),
    ("BTS3003", "this decorator returns `{}`, which a field decorator cannot return", 1270),
    ("BTS3003", "this decorator returns `{}`, which a method decorator cannot return", 1270),
    ("BTS3003", "this decorator returns `{}`, which a parameter decorator cannot return", 1271),
    ("BTS3003", "this element has children but its props declare no `{}`", 2322),
    ("BTS3003", "unable to resolve the signature of this class decorator when called as an expression (it must accept {n} argument(s))", 1238),
    ("BTS3003", "unable to resolve the signature of this field decorator when called as an expression (it must accept {n} argument(s))", 1240),
    ("BTS3003", "unable to resolve the signature of this parameter decorator when called as an expression (it must accept {n} argument(s))", 1239),
    ("BTS3004", "a return statement cannot be used inside a class static block", 18041),
    ("BTS3004", "class method return type `{}` is not assignable to `{}`", 2322),
    ("BTS3004", "class method with return type `{}` can complete without returning a value", 2366),
    ("BTS3004", "constructor return type `{}` is not assignable to class `{}`", 2741),
    ("BTS3004", "not all code paths return a value", 7030),
    ("BTS3004", "return expression has type `{}`, which is not assignable to `{}`", 2322),
    ("BTS3005", "TS2448: `{}` is used before its declaration", 2448),
    ("BTS3005", "TS2449: `{}` is used before its declaration", 2449),
    ("BTS3005", "TS2449: class {} is used before its declaration", 2449),
    ("BTS3006", "TS2588: cannot assign to `{}` because it is a constant", 2588),
    ("BTS3006", "TS2628: cannot assign to `{}` because it is an enum", 2628),
    ("BTS3006", "TS2629: cannot assign to `{}` because it is a class", 2629),
    ("BTS3006", "TS2630: cannot assign to `{}` because it is a function", 2630),
    ("BTS3006", "TS2631: cannot assign to `{}` because it is a namespace", 2631),
    ("BTS3006", "TS2632: cannot assign to `{}` because it is an import", 2632),
    ("BTS1001", "decorators cannot be applied to both the getter and the setter of the same name", 1207),
];
