[package]
name = "blueice-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
blueice-dom = { path = "../dom" }
blueice-html = { path = "../html" }
blueice-css = { path = "../css" }
blueice-layout = { path = "../layout" }
blueice-paint = { path = "../paint" }
