[package]
name = "blueice-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
blueice-dom = { path = "../dom" }
blueice-html = { path = "../html" }
blueice-css = { path = "../css" }
blueice-layout = { path = "../layout" }
blueice-paint = { path = "../paint" }
blueice-raster = { path = "../raster" }
blueice-net = { path = "../../net" }
blueice-ipc = { path = "../../ipc" }
blueice-i18n = { path = "../../i18n" }

[dev-dependencies]
blueice-testing = { path = "../../testing" }
