[package]
name = "blueice-extension-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
blueice-ipc = { path = "../ipc" }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
url = "2"
wasmtime = { version = "49.0.0", default-features = false, features = ["cranelift", "runtime"] }

[dev-dependencies]
wat = "1"
