// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Generation-bound code-unit identities for compiled structured programs.
//!
//! This is deliberately a validation and lifetime boundary, not a debugger
//! implementation. A page host can retain a [`BlueJsProgramHandle`] together
//! with its source identity, enumerate the instruction boundaries accepted by
//! the exact generated bytecode, and reject stale or malformed locations.
//! Pausing, stack inspection, AST node identities, and source-span mapping
//! remain owned by the page-host and debugger work.

use crate::{BlueJsProgramV1, Bytecode, CompileError};
use std::collections::BTreeMap;
use std::fmt;

/// The public format of code-unit and instruction-boundary identities.
pub const BLUEJS_PROGRAM_DEBUG_ABI_V1: &str = "bluejs-program-debug-v1";

/// A monotonically assigned generation for one compiled program installed in
/// a [`BlueJsProgramRegistry`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsProgramGeneration(u64);

impl BlueJsProgramGeneration {
    /// The opaque generation value for IPC or persisted diagnostic records.
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

/// A live compiled program registered by a page host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsProgramHandle {
    generation: BlueJsProgramGeneration,
}

impl BlueJsProgramHandle {
    /// The generation associated with this handle.
    pub fn generation(self) -> BlueJsProgramGeneration {
        self.generation
    }
}

/// An opaque source identity supplied by the caller-authorized page loader.
///
/// BlueJS does not open files or resolve URLs at this boundary. The loader
/// therefore supplies the canonical module identity and content fingerprint
/// that it already authorized, and the registry retains them unchanged for
/// the installed program generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlueJsSourceIdentity {
    canonical_module_id: String,
    source_hash: String,
}

impl BlueJsSourceIdentity {
    /// Creates a non-empty opaque source identity.
    pub fn new(
        canonical_module_id: impl Into<String>,
        source_hash: impl Into<String>,
    ) -> Result<Self, BlueJsProgramDebugError> {
        let canonical_module_id = canonical_module_id.into();
        let source_hash = source_hash.into();
        if canonical_module_id.is_empty() {
            return Err(BlueJsProgramDebugError::EmptyCanonicalModuleId);
        }
        if source_hash.is_empty() {
            return Err(BlueJsProgramDebugError::EmptySourceHash);
        }
        Ok(Self {
            canonical_module_id,
            source_hash,
        })
    }

    /// The host-authorized canonical module identity.
    pub fn canonical_module_id(&self) -> &str {
        &self.canonical_module_id
    }

    /// The exact source-content fingerprint supplied by the host.
    pub fn source_hash(&self) -> &str {
        &self.source_hash
    }
}

/// One deterministic code-unit identity within a program generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsCodeUnitId {
    generation: BlueJsProgramGeneration,
    ordinal: u32,
}

impl BlueJsCodeUnitId {
    /// The program generation that owns this code unit.
    pub fn generation(self) -> BlueJsProgramGeneration {
        self.generation
    }

    /// The deterministic pre-order index inside the owning program.
    pub fn ordinal(self) -> u32 {
        self.ordinal
    }
}

/// A validated bytecode instruction boundary within one code unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsSafePoint {
    /// The code unit containing this instruction.
    pub code_unit: BlueJsCodeUnitId,
    /// The instruction's byte offset within the code unit.
    pub bytecode_offset: u32,
}

/// Metadata for one generated code unit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlueJsCodeUnitInfo {
    id: BlueJsCodeUnitId,
    instruction_offsets: Vec<u32>,
}

impl BlueJsCodeUnitInfo {
    /// The generation-bound identity of this code unit.
    pub fn id(&self) -> BlueJsCodeUnitId {
        self.id
    }

    /// Instruction boundaries that this code unit accepts as safe points.
    pub fn instruction_offsets(&self) -> &[u32] {
        &self.instruction_offsets
    }
}

/// A compiled structured program plus its immutable code-unit metadata.
#[derive(Clone)]
pub struct BlueJsCompiledProgram {
    handle: BlueJsProgramHandle,
    source: BlueJsSourceIdentity,
    bytecode: Bytecode,
    code_units: Vec<BlueJsCodeUnitInfo>,
}

impl BlueJsCompiledProgram {
    /// The installed handle that owns this artifact.
    pub fn handle(&self) -> BlueJsProgramHandle {
        self.handle
    }

    /// The exact host-supplied source identity retained for this generation.
    pub fn source(&self) -> &BlueJsSourceIdentity {
        &self.source
    }

    /// The root bytecode that BlueJS will execute for this program.
    pub fn bytecode(&self) -> &Bytecode {
        &self.bytecode
    }

    /// The root-first, pre-order code-unit inventory.
    pub fn code_units(&self) -> &[BlueJsCodeUnitInfo] {
        &self.code_units
    }

    /// Every valid instruction boundary in deterministic code-unit order.
    pub fn safe_points(&self) -> impl Iterator<Item = BlueJsSafePoint> + '_ {
        self.code_units.iter().flat_map(|unit| {
            unit.instruction_offsets
                .iter()
                .copied()
                .map(move |bytecode_offset| BlueJsSafePoint {
                    code_unit: unit.id,
                    bytecode_offset,
                })
        })
    }

    fn validate_safe_point(
        &self,
        safe_point: BlueJsSafePoint,
    ) -> Result<(), BlueJsProgramDebugError> {
        if safe_point.code_unit.generation != self.handle.generation {
            return Err(BlueJsProgramDebugError::StaleSafePoint);
        }
        let unit = self
            .code_units
            .get(safe_point.code_unit.ordinal as usize)
            .ok_or(BlueJsProgramDebugError::UnknownCodeUnit)?;
        if unit.id != safe_point.code_unit {
            return Err(BlueJsProgramDebugError::UnknownCodeUnit);
        }
        if !unit
            .instruction_offsets
            .contains(&safe_point.bytecode_offset)
        {
            return Err(BlueJsProgramDebugError::InvalidInstructionBoundary);
        }
        Ok(())
    }
}

/// Failure to install, replace, or validate a generation-bound program ID.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlueJsProgramDebugError {
    /// The host did not supply a canonical source identity.
    EmptyCanonicalModuleId,
    /// The host did not supply an exact source-content fingerprint.
    EmptySourceHash,
    /// The structured program could not be compiled to bytecode.
    Compilation(CompileError),
    /// The registry has exhausted its non-reusable generation space.
    GenerationExhausted,
    /// The compiler produced more code units than this v1 identity can name.
    CodeUnitLimitExceeded,
    /// The program handle was never registered or has been invalidated.
    UnknownProgram,
    /// The supplied safe point belongs to a different program generation.
    StaleSafePoint,
    /// The code-unit component is not present in the named generation.
    UnknownCodeUnit,
    /// The offset is not the beginning of a generated instruction.
    InvalidInstructionBoundary,
}

impl fmt::Display for BlueJsProgramDebugError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyCanonicalModuleId => f.write_str("canonical module ID must not be empty"),
            Self::EmptySourceHash => f.write_str("source hash must not be empty"),
            Self::Compilation(error) => write!(f, "cannot compile structured program: {error}"),
            Self::GenerationExhausted => {
                f.write_str("BlueJS program generation space is exhausted")
            }
            Self::CodeUnitLimitExceeded => f.write_str("BlueJS program has too many code units"),
            Self::UnknownProgram => f.write_str("BlueJS program handle is stale or unknown"),
            Self::StaleSafePoint => f.write_str("BlueJS safe point belongs to another generation"),
            Self::UnknownCodeUnit => f.write_str("BlueJS code unit is unknown for this generation"),
            Self::InvalidInstructionBoundary => {
                f.write_str("BlueJS offset is not an instruction boundary")
            }
        }
    }
}

impl std::error::Error for BlueJsProgramDebugError {}

impl From<CompileError> for BlueJsProgramDebugError {
    fn from(error: CompileError) -> Self {
        Self::Compilation(error)
    }
}

/// The host-owned lifetime table for compiled page programs.
///
/// Registering a replacement allocates a new generation only after the new
/// program has compiled and its metadata is complete. Invalidating or
/// replacing a program removes the prior generation, so a code-unit ID can
/// never be accidentally reinterpreted for successor bytecode.
pub struct BlueJsProgramRegistry {
    next_generation: u64,
    programs: BTreeMap<BlueJsProgramGeneration, BlueJsCompiledProgram>,
}

impl Default for BlueJsProgramRegistry {
    fn default() -> Self {
        Self {
            next_generation: 1,
            programs: BTreeMap::new(),
        }
    }
}

impl BlueJsProgramRegistry {
    /// The ABI label a host records alongside this registry's IDs.
    pub const ABI: &'static str = BLUEJS_PROGRAM_DEBUG_ABI_V1;

    /// Compiles and installs a new program under a fresh generation.
    pub fn install(
        &mut self,
        source: BlueJsSourceIdentity,
        program: &BlueJsProgramV1,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        let bytecode = program.compile()?;
        self.install_compiled(source, bytecode)
    }

    /// Replaces a live program without exposing a partial replacement on
    /// compilation failure. A successful replacement invalidates every old
    /// code-unit and safe-point identity.
    pub fn replace(
        &mut self,
        previous: BlueJsProgramHandle,
        source: BlueJsSourceIdentity,
        program: &BlueJsProgramV1,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        if !self.programs.contains_key(&previous.generation) {
            return Err(BlueJsProgramDebugError::UnknownProgram);
        }
        let bytecode = program.compile()?;
        let replacement = self.install_compiled(source, bytecode)?;
        self.programs.remove(&previous.generation);
        Ok(replacement)
    }

    /// Explicitly drops a program generation, for navigation, cache eviction,
    /// hibernation, or tab teardown.
    pub fn invalidate(&mut self, handle: BlueJsProgramHandle) -> bool {
        self.programs.remove(&handle.generation).is_some()
    }

    /// Retrieves only a currently-live compiled program.
    pub fn get(
        &self,
        handle: BlueJsProgramHandle,
    ) -> Result<&BlueJsCompiledProgram, BlueJsProgramDebugError> {
        self.programs
            .get(&handle.generation)
            .ok_or(BlueJsProgramDebugError::UnknownProgram)
    }

    /// Checks that `safe_point` names an instruction in `handle`'s exact live
    /// generation. This is intentionally a validation API, not heuristic
    /// source remapping.
    pub fn validate_safe_point(
        &self,
        handle: BlueJsProgramHandle,
        safe_point: BlueJsSafePoint,
    ) -> Result<(), BlueJsProgramDebugError> {
        if safe_point.code_unit.generation != handle.generation {
            return Err(BlueJsProgramDebugError::StaleSafePoint);
        }
        self.get(handle)?.validate_safe_point(safe_point)
    }

    fn install_compiled(
        &mut self,
        source: BlueJsSourceIdentity,
        bytecode: Bytecode,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        let generation = BlueJsProgramGeneration(self.next_generation);
        self.next_generation = self
            .next_generation
            .checked_add(1)
            .ok_or(BlueJsProgramDebugError::GenerationExhausted)?;
        let handle = BlueJsProgramHandle { generation };
        let mut code_units = Vec::new();
        collect_code_units(&bytecode, generation, &mut code_units)?;
        self.programs.insert(
            generation,
            BlueJsCompiledProgram {
                handle,
                source,
                bytecode,
                code_units,
            },
        );
        Ok(handle)
    }
}

fn collect_code_units(
    bytecode: &Bytecode,
    generation: BlueJsProgramGeneration,
    code_units: &mut Vec<BlueJsCodeUnitInfo>,
) -> Result<(), BlueJsProgramDebugError> {
    let ordinal = u32::try_from(code_units.len())
        .map_err(|_| BlueJsProgramDebugError::CodeUnitLimitExceeded)?;
    let instruction_offsets = bytecode
        .instructions()
        .map(|instruction| {
            u32::try_from(instruction.offset)
                .map_err(|_| BlueJsProgramDebugError::InvalidInstructionBoundary)
        })
        .collect::<Result<Vec<_>, _>>()?;
    code_units.push(BlueJsCodeUnitInfo {
        id: BlueJsCodeUnitId {
            generation,
            ordinal,
        },
        instruction_offsets,
    });
    for child in bytecode.child_code_units() {
        collect_code_units(child, generation, code_units)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{parse, BlueJsProgramV1, Value, Vm};

    fn source(name: &str, hash: &str) -> BlueJsSourceIdentity {
        BlueJsSourceIdentity::new(name, hash).unwrap()
    }

    fn script(text: &str) -> BlueJsProgramV1 {
        BlueJsProgramV1::Script(parse(text).unwrap())
    }

    #[test]
    fn registry_exposes_and_validates_exact_instruction_boundaries() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(source("page:///main.js", "sha256:one"), &script("1 + 2"))
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(compiled.source().canonical_module_id(), "page:///main.js");
        assert_eq!(compiled.source().source_hash(), "sha256:one");
        assert_eq!(
            Vm::default().execute(compiled.bytecode()).unwrap(),
            Value::Number(3.0)
        );
        let safe_point = compiled.safe_points().next().unwrap();
        registry.validate_safe_point(handle, safe_point).unwrap();
        assert_eq!(safe_point.code_unit.generation(), handle.generation());
        assert_eq!(safe_point.code_unit.ordinal(), 0);

        let malformed = BlueJsSafePoint {
            code_unit: safe_point.code_unit,
            bytecode_offset: safe_point.bytecode_offset + 1,
        };
        assert_eq!(
            registry.validate_safe_point(handle, malformed),
            Err(BlueJsProgramDebugError::InvalidInstructionBoundary)
        );
    }

    #[test]
    fn nested_function_code_units_are_named_in_preorder() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(
                source("page:///nested.js", "sha256:nested"),
                &script("function answer(){return 42;} answer();"),
            )
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(compiled.code_units().len(), 2);
        assert_eq!(compiled.code_units()[0].id().ordinal(), 0);
        assert_eq!(compiled.code_units()[1].id().ordinal(), 1);
        let nested_safe_point = BlueJsSafePoint {
            code_unit: compiled.code_units()[1].id(),
            bytecode_offset: compiled.code_units()[1].instruction_offsets()[0],
        };
        registry
            .validate_safe_point(handle, nested_safe_point)
            .unwrap();
    }

    #[test]
    fn replacing_or_invalidating_a_program_fails_closed_for_old_ids() {
        let mut registry = BlueJsProgramRegistry::default();
        let first = registry
            .install(source("page:///main.js", "sha256:old"), &script("1"))
            .unwrap();
        let stale_safe_point = registry.get(first).unwrap().safe_points().next().unwrap();
        let second = registry
            .replace(first, source("page:///main.js", "sha256:new"), &script("2"))
            .unwrap();
        assert_ne!(first.generation(), second.generation());
        assert!(matches!(
            registry.get(first),
            Err(BlueJsProgramDebugError::UnknownProgram)
        ));
        assert_eq!(
            registry.validate_safe_point(first, stale_safe_point),
            Err(BlueJsProgramDebugError::UnknownProgram)
        );
        assert_eq!(
            registry.validate_safe_point(second, stale_safe_point),
            Err(BlueJsProgramDebugError::StaleSafePoint)
        );
        assert!(registry.invalidate(second));
        assert!(!registry.invalidate(second));
    }

    #[test]
    fn failed_replacement_preserves_the_previous_generation() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(source("page:///main.js", "sha256:old"), &script("1"))
            .unwrap();
        let invalid = script("let duplicate; let duplicate;");
        assert!(matches!(
            registry.replace(handle, source("page:///main.js", "sha256:bad"), &invalid),
            Err(BlueJsProgramDebugError::Compilation(
                CompileError::DuplicateBinding(_)
            ))
        ));
        assert_eq!(
            Vm::default()
                .execute(registry.get(handle).unwrap().bytecode())
                .unwrap(),
            Value::Number(1.0)
        );
    }

    #[test]
    fn source_identity_rejects_missing_required_fields() {
        assert_eq!(
            BlueJsSourceIdentity::new("", "sha256:value"),
            Err(BlueJsProgramDebugError::EmptyCanonicalModuleId)
        );
        assert_eq!(
            BlueJsSourceIdentity::new("page:///main.js", ""),
            Err(BlueJsProgramDebugError::EmptySourceHash)
        );
    }
}
