// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//! Generation-bound code-unit identities for compiled structured programs.
//!
//! This is deliberately a validation and lifetime boundary, not a debugger
//! implementation. A page host can retain a [`BlueJsProgramHandle`] together
//! with its source identity, enumerate the instruction boundaries accepted by
//! the exact generated bytecode, resolve top-level AST statements to their
//! compiler-recorded instruction starts, and reject stale or malformed
//! locations. Page lifetime ownership, pausing, stack inspection, and complete
//! source-span mapping remain owned by the page-host and debugger work.

use crate::{BlueJsProgramV1, Bytecode, CompileError};
mod ast_ids;
use ast_ids::collect_ast_nodes;
use std::collections::BTreeMap;
use std::fmt;

/// The public format of code-unit and instruction-boundary identities.
pub const BLUEJS_PROGRAM_DEBUG_ABI_V1: &str = "bluejs-program-debug-v1";

/// A monotonically assigned generation for one compiled program installed in
/// a [`BlueJsProgramRegistry`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsProgramGeneration(u64);

impl BlueJsProgramGeneration {
    /// The opaque generation value for IPC or persisted diagnostic records.
    pub fn as_u64(self) -> u64 {
        self.0
    }
}

/// A live compiled program registered by a page host.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsProgramHandle {
    generation: BlueJsProgramGeneration,
}

impl BlueJsProgramHandle {
    /// The generation associated with this handle.
    pub fn generation(self) -> BlueJsProgramGeneration {
        self.generation
    }
}

/// An opaque source identity supplied by the caller-authorized page loader.
///
/// BlueJS does not open files or resolve URLs at this boundary. The loader
/// therefore supplies the canonical module identity and content fingerprint
/// that it already authorized, and the registry retains them unchanged for
/// the installed program generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlueJsSourceIdentity {
    canonical_module_id: String,
    source_hash: String,
}

impl BlueJsSourceIdentity {
    /// Creates a non-empty opaque source identity.
    pub fn new(
        canonical_module_id: impl Into<String>,
        source_hash: impl Into<String>,
    ) -> Result<Self, BlueJsProgramDebugError> {
        let canonical_module_id = canonical_module_id.into();
        let source_hash = source_hash.into();
        if canonical_module_id.is_empty() {
            return Err(BlueJsProgramDebugError::EmptyCanonicalModuleId);
        }
        if source_hash.is_empty() {
            return Err(BlueJsProgramDebugError::EmptySourceHash);
        }
        Ok(Self {
            canonical_module_id,
            source_hash,
        })
    }

    /// The host-authorized canonical module identity.
    pub fn canonical_module_id(&self) -> &str {
        &self.canonical_module_id
    }

    /// The exact source-content fingerprint supplied by the host.
    pub fn source_hash(&self) -> &str {
        &self.source_hash
    }
}

/// One deterministic code-unit identity within a program generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsCodeUnitId {
    generation: BlueJsProgramGeneration,
    ordinal: u32,
}

/// One deterministic executable AST-node identity within a program generation.
///
/// This v1 inventory names the structured-program root and every statement or
/// expression that can contribute executable behavior. Binding patterns and
/// declarative module entries are traversed for executable children but are
/// not independently named.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsAstNodeId {
    generation: BlueJsProgramGeneration,
    ordinal: u32,
}

impl BlueJsAstNodeId {
    /// The program generation that owns this AST node.
    pub fn generation(self) -> BlueJsProgramGeneration {
        self.generation
    }

    /// The deterministic pre-order index inside the owning structured AST.
    pub fn ordinal(self) -> u32 {
        self.ordinal
    }
}

/// The executable AST shape identified by [`BlueJsAstNodeId`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BlueJsAstNodeKind {
    /// The root of a classic-script structured program.
    Script,
    /// The root of an ECMAScript module structured program.
    Module,
    /// An executable statement.
    Statement,
    /// An executable expression.
    Expression,
}

/// Metadata for one generation-bound executable AST node.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BlueJsAstNodeInfo {
    id: BlueJsAstNodeId,
    kind: BlueJsAstNodeKind,
    top_level_statement: bool,
}

impl BlueJsAstNodeInfo {
    /// The generation-bound AST-node identity.
    pub fn id(&self) -> BlueJsAstNodeId {
        self.id
    }

    /// The executable AST shape at this identity.
    pub fn kind(&self) -> BlueJsAstNodeKind {
        self.kind
    }

    /// Whether this node is a direct child statement of the program root.
    ///
    /// This explicit structural flag lets a source front end associate its
    /// ordered top-level lowering records without inferring tree depth from a
    /// numeric node ordinal.
    pub fn is_top_level_statement(&self) -> bool {
        self.top_level_statement
    }
}

#[derive(Clone, Copy)]
struct AstNodeDescriptor {
    kind: BlueJsAstNodeKind,
    top_level_statement: bool,
}

impl BlueJsCodeUnitId {
    /// The program generation that owns this code unit.
    pub fn generation(self) -> BlueJsProgramGeneration {
        self.generation
    }

    /// The deterministic pre-order index inside the owning program.
    pub fn ordinal(self) -> u32 {
        self.ordinal
    }
}

/// A validated bytecode instruction boundary within one code unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct BlueJsSafePoint {
    /// The code unit containing this instruction.
    pub code_unit: BlueJsCodeUnitId,
    /// The instruction's byte offset within the code unit.
    pub bytecode_offset: u32,
}

/// Metadata for one generated code unit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BlueJsCodeUnitInfo {
    id: BlueJsCodeUnitId,
    instruction_offsets: Vec<u32>,
}

impl BlueJsCodeUnitInfo {
    /// The generation-bound identity of this code unit.
    pub fn id(&self) -> BlueJsCodeUnitId {
        self.id
    }

    /// Instruction boundaries that this code unit accepts as safe points.
    pub fn instruction_offsets(&self) -> &[u32] {
        &self.instruction_offsets
    }
}

/// A compiled structured program plus its immutable code-unit metadata.
#[derive(Clone)]
pub struct BlueJsCompiledProgram {
    handle: BlueJsProgramHandle,
    source: BlueJsSourceIdentity,
    bytecode: Bytecode,
    code_units: Vec<BlueJsCodeUnitInfo>,
    ast_nodes: Vec<BlueJsAstNodeInfo>,
    ast_safe_points: BTreeMap<BlueJsAstNodeId, BlueJsSafePoint>,
}

impl BlueJsCompiledProgram {
    /// The installed handle that owns this artifact.
    pub fn handle(&self) -> BlueJsProgramHandle {
        self.handle
    }

    /// The exact host-supplied source identity retained for this generation.
    pub fn source(&self) -> &BlueJsSourceIdentity {
        &self.source
    }

    /// The root bytecode that BlueJS will execute for this program.
    pub fn bytecode(&self) -> &Bytecode {
        &self.bytecode
    }

    /// The root-first, pre-order code-unit inventory.
    pub fn code_units(&self) -> &[BlueJsCodeUnitInfo] {
        &self.code_units
    }

    /// The root-first pre-order inventory of executable structured AST nodes.
    pub fn ast_nodes(&self) -> &[BlueJsAstNodeInfo] {
        &self.ast_nodes
    }

    /// Every valid instruction boundary in deterministic code-unit order.
    pub fn safe_points(&self) -> impl Iterator<Item = BlueJsSafePoint> + '_ {
        self.code_units.iter().flat_map(|unit| {
            unit.instruction_offsets
                .iter()
                .copied()
                .map(move |bytecode_offset| BlueJsSafePoint {
                    code_unit: unit.id,
                    bytecode_offset,
                })
        })
    }

    /// Returns the compiler-recorded root-code-unit safe point for an
    /// executable AST node, or an explicit unbound error when that node emits
    /// no root instruction.
    pub fn safe_point_for_ast_node(
        &self,
        node: BlueJsAstNodeId,
    ) -> Result<BlueJsSafePoint, BlueJsProgramDebugError> {
        self.validate_ast_node(node)?;
        self.ast_safe_points
            .get(&node)
            .copied()
            .ok_or(BlueJsProgramDebugError::AstNodeUnbound)
    }

    fn validate_safe_point(
        &self,
        safe_point: BlueJsSafePoint,
    ) -> Result<(), BlueJsProgramDebugError> {
        if safe_point.code_unit.generation != self.handle.generation {
            return Err(BlueJsProgramDebugError::StaleSafePoint);
        }
        let unit = self
            .code_units
            .get(safe_point.code_unit.ordinal as usize)
            .ok_or(BlueJsProgramDebugError::UnknownCodeUnit)?;
        if unit.id != safe_point.code_unit {
            return Err(BlueJsProgramDebugError::UnknownCodeUnit);
        }
        if !unit
            .instruction_offsets
            .contains(&safe_point.bytecode_offset)
        {
            return Err(BlueJsProgramDebugError::InvalidInstructionBoundary);
        }
        Ok(())
    }

    fn validate_ast_node(&self, node: BlueJsAstNodeId) -> Result<(), BlueJsProgramDebugError> {
        if node.generation != self.handle.generation {
            return Err(BlueJsProgramDebugError::StaleAstNode);
        }
        let known = self
            .ast_nodes
            .get(node.ordinal as usize)
            .is_some_and(|candidate| candidate.id == node);
        if known {
            Ok(())
        } else {
            Err(BlueJsProgramDebugError::UnknownAstNode)
        }
    }
}

/// Failure to install, replace, or validate a generation-bound program ID.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BlueJsProgramDebugError {
    /// The host did not supply a canonical source identity.
    EmptyCanonicalModuleId,
    /// The host did not supply an exact source-content fingerprint.
    EmptySourceHash,
    /// The structured program could not be compiled to bytecode.
    Compilation(CompileError),
    /// The registry has exhausted its non-reusable generation space.
    GenerationExhausted,
    /// The compiler produced more code units than this v1 identity can name.
    CodeUnitLimitExceeded,
    /// The compiler produced more executable AST nodes than this v1 identity
    /// can name.
    AstNodeLimitExceeded,
    /// The program handle was never registered or has been invalidated.
    UnknownProgram,
    /// The supplied safe point belongs to a different program generation.
    StaleSafePoint,
    /// The code-unit component is not present in the named generation.
    UnknownCodeUnit,
    /// The offset is not the beginning of a generated instruction.
    InvalidInstructionBoundary,
    /// The AST-node identity belongs to a different program generation.
    StaleAstNode,
    /// The AST-node component is absent from the named generation.
    UnknownAstNode,
    /// The executable AST node has no compiler-recorded root instruction.
    AstNodeUnbound,
    /// Compiler top-level statement provenance disagreed with the structured
    /// AST inventory and was rejected rather than guessed.
    AstBytecodeShapeMismatch,
}

impl fmt::Display for BlueJsProgramDebugError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyCanonicalModuleId => f.write_str("canonical module ID must not be empty"),
            Self::EmptySourceHash => f.write_str("source hash must not be empty"),
            Self::Compilation(error) => write!(f, "cannot compile structured program: {error}"),
            Self::GenerationExhausted => {
                f.write_str("BlueJS program generation space is exhausted")
            }
            Self::CodeUnitLimitExceeded => f.write_str("BlueJS program has too many code units"),
            Self::AstNodeLimitExceeded => f.write_str("BlueJS program has too many AST nodes"),
            Self::UnknownProgram => f.write_str("BlueJS program handle is stale or unknown"),
            Self::StaleSafePoint => f.write_str("BlueJS safe point belongs to another generation"),
            Self::UnknownCodeUnit => f.write_str("BlueJS code unit is unknown for this generation"),
            Self::InvalidInstructionBoundary => {
                f.write_str("BlueJS offset is not an instruction boundary")
            }
            Self::StaleAstNode => f.write_str("BlueJS AST node belongs to another generation"),
            Self::UnknownAstNode => f.write_str("BlueJS AST node is unknown for this generation"),
            Self::AstNodeUnbound => {
                f.write_str("BlueJS AST node has no executable root safe point")
            }
            Self::AstBytecodeShapeMismatch => {
                f.write_str("BlueJS AST and bytecode top-level provenance disagree")
            }
        }
    }
}

impl std::error::Error for BlueJsProgramDebugError {}

impl From<CompileError> for BlueJsProgramDebugError {
    fn from(error: CompileError) -> Self {
        Self::Compilation(error)
    }
}

/// The host-owned lifetime table for compiled page programs.
///
/// Registering a replacement allocates a new generation only after the new
/// program has compiled and its metadata is complete. Invalidating or
/// replacing a program removes the prior generation, so a code-unit ID can
/// never be accidentally reinterpreted for successor bytecode.
pub struct BlueJsProgramRegistry {
    next_generation: u64,
    programs: BTreeMap<BlueJsProgramGeneration, BlueJsCompiledProgram>,
}

impl Default for BlueJsProgramRegistry {
    fn default() -> Self {
        Self {
            next_generation: 1,
            programs: BTreeMap::new(),
        }
    }
}

impl BlueJsProgramRegistry {
    /// The ABI label a host records alongside this registry's IDs.
    pub const ABI: &'static str = BLUEJS_PROGRAM_DEBUG_ABI_V1;

    /// Compiles and installs a new program under a fresh generation.
    pub fn install(
        &mut self,
        source: BlueJsSourceIdentity,
        program: &BlueJsProgramV1,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        let bytecode = program.compile()?;
        let ast_nodes = collect_ast_nodes(program);
        self.install_with_ast_nodes(source, bytecode, ast_nodes)
    }

    /// Installs bytecode already compiled by BlueJS together with the exact
    /// source identity authorized by the embedding host.
    ///
    /// This lets a front-end bridge hand off its existing BlueJS bytecode
    /// without a generated-source round trip or a second compilation pass.
    /// Callers still need to retain the structured-program ABI and their own
    /// compiler fingerprints at the higher-level host boundary.
    pub fn install_precompiled(
        &mut self,
        source: BlueJsSourceIdentity,
        bytecode: Bytecode,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        self.install_with_ast_nodes(source, bytecode, Vec::new())
    }

    fn install_with_ast_nodes(
        &mut self,
        source: BlueJsSourceIdentity,
        bytecode: Bytecode,
        ast_descriptors: Vec<AstNodeDescriptor>,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        let generation = BlueJsProgramGeneration(self.next_generation);
        self.next_generation = self
            .next_generation
            .checked_add(1)
            .ok_or(BlueJsProgramDebugError::GenerationExhausted)?;
        let handle = BlueJsProgramHandle { generation };
        let mut code_units = Vec::new();
        collect_code_units(&bytecode, generation, &mut code_units)?;
        let ast_nodes = ast_descriptors
            .into_iter()
            .enumerate()
            .map(|(ordinal, descriptor)| {
                Ok(BlueJsAstNodeInfo {
                    id: BlueJsAstNodeId {
                        generation,
                        ordinal: u32::try_from(ordinal)
                            .map_err(|_| BlueJsProgramDebugError::AstNodeLimitExceeded)?,
                    },
                    kind: descriptor.kind,
                    top_level_statement: descriptor.top_level_statement,
                })
            })
            .collect::<Result<Vec<_>, BlueJsProgramDebugError>>()?;
        let mut ast_safe_points = BTreeMap::new();
        if !ast_nodes.is_empty() {
            let top_level_nodes = ast_nodes
                .iter()
                .filter(|node| node.top_level_statement)
                .collect::<Vec<_>>();
            if top_level_nodes.len() != bytecode.root_statement_offsets().len() {
                return Err(BlueJsProgramDebugError::AstBytecodeShapeMismatch);
            }
            let root_code_unit = code_units
                .first()
                .expect("every compiled BlueJS program has a root code unit")
                .id;
            for (node, offset) in top_level_nodes
                .into_iter()
                .zip(bytecode.root_statement_offsets())
            {
                let Some(bytecode_offset) = offset else {
                    continue;
                };
                if !code_units[0].instruction_offsets.contains(bytecode_offset) {
                    return Err(BlueJsProgramDebugError::AstBytecodeShapeMismatch);
                }
                ast_safe_points.insert(
                    node.id,
                    BlueJsSafePoint {
                        code_unit: root_code_unit,
                        bytecode_offset: *bytecode_offset,
                    },
                );
            }
        }
        self.programs.insert(
            generation,
            BlueJsCompiledProgram {
                handle,
                source,
                bytecode,
                code_units,
                ast_nodes,
                ast_safe_points,
            },
        );
        Ok(handle)
    }

    /// Replaces a live program without exposing a partial replacement on
    /// compilation failure. A successful replacement invalidates every old
    /// code-unit and safe-point identity.
    pub fn replace(
        &mut self,
        previous: BlueJsProgramHandle,
        source: BlueJsSourceIdentity,
        program: &BlueJsProgramV1,
    ) -> Result<BlueJsProgramHandle, BlueJsProgramDebugError> {
        if !self.programs.contains_key(&previous.generation) {
            return Err(BlueJsProgramDebugError::UnknownProgram);
        }
        let bytecode = program.compile()?;
        let ast_nodes = collect_ast_nodes(program);
        let replacement = self.install_with_ast_nodes(source, bytecode, ast_nodes)?;
        self.programs.remove(&previous.generation);
        Ok(replacement)
    }

    /// Explicitly drops a program generation, for navigation, cache eviction,
    /// hibernation, or tab teardown.
    pub fn invalidate(&mut self, handle: BlueJsProgramHandle) -> bool {
        self.programs.remove(&handle.generation).is_some()
    }

    /// Retrieves only a currently-live compiled program.
    pub fn get(
        &self,
        handle: BlueJsProgramHandle,
    ) -> Result<&BlueJsCompiledProgram, BlueJsProgramDebugError> {
        self.programs
            .get(&handle.generation)
            .ok_or(BlueJsProgramDebugError::UnknownProgram)
    }

    /// Checks that `safe_point` names an instruction in `handle`'s exact live
    /// generation. This is intentionally a validation API, not heuristic
    /// source remapping.
    pub fn validate_safe_point(
        &self,
        handle: BlueJsProgramHandle,
        safe_point: BlueJsSafePoint,
    ) -> Result<(), BlueJsProgramDebugError> {
        if safe_point.code_unit.generation != handle.generation {
            return Err(BlueJsProgramDebugError::StaleSafePoint);
        }
        self.get(handle)?.validate_safe_point(safe_point)
    }

    /// Checks that `node` names an executable AST node in `handle`'s exact
    /// live generation. Precompiled-only installations deliberately have no
    /// AST inventory and therefore reject every AST-node lookup.
    pub fn validate_ast_node(
        &self,
        handle: BlueJsProgramHandle,
        node: BlueJsAstNodeId,
    ) -> Result<(), BlueJsProgramDebugError> {
        if node.generation != handle.generation {
            return Err(BlueJsProgramDebugError::StaleAstNode);
        }
        self.get(handle)?.validate_ast_node(node)
    }

    /// Resolves one verified executable AST node to its compiler-recorded
    /// root-code-unit safe point. There is no nearest-offset fallback.
    pub fn safe_point_for_ast_node(
        &self,
        handle: BlueJsProgramHandle,
        node: BlueJsAstNodeId,
    ) -> Result<BlueJsSafePoint, BlueJsProgramDebugError> {
        if node.generation != handle.generation {
            return Err(BlueJsProgramDebugError::StaleAstNode);
        }
        self.get(handle)?.safe_point_for_ast_node(node)
    }
}

fn collect_code_units(
    bytecode: &Bytecode,
    generation: BlueJsProgramGeneration,
    code_units: &mut Vec<BlueJsCodeUnitInfo>,
) -> Result<(), BlueJsProgramDebugError> {
    let ordinal = u32::try_from(code_units.len())
        .map_err(|_| BlueJsProgramDebugError::CodeUnitLimitExceeded)?;
    let instruction_offsets = bytecode
        .instructions()
        .map(|instruction| {
            u32::try_from(instruction.offset)
                .map_err(|_| BlueJsProgramDebugError::InvalidInstructionBoundary)
        })
        .collect::<Result<Vec<_>, _>>()?;
    code_units.push(BlueJsCodeUnitInfo {
        id: BlueJsCodeUnitId {
            generation,
            ordinal,
        },
        instruction_offsets,
    });
    for child in bytecode.child_code_units() {
        collect_code_units(child, generation, code_units)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{parse, BlueJsProgramV1, Value, Vm};

    fn source(name: &str, hash: &str) -> BlueJsSourceIdentity {
        BlueJsSourceIdentity::new(name, hash).unwrap()
    }

    fn script(text: &str) -> BlueJsProgramV1 {
        BlueJsProgramV1::Script(parse(text).unwrap())
    }

    #[test]
    fn registry_exposes_and_validates_exact_instruction_boundaries() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(source("page:///main.js", "sha256:one"), &script("1 + 2"))
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(compiled.source().canonical_module_id(), "page:///main.js");
        assert_eq!(compiled.source().source_hash(), "sha256:one");
        assert_eq!(
            Vm::default().execute(compiled.bytecode()).unwrap(),
            Value::Number(3.0)
        );
        let safe_point = compiled.safe_points().next().unwrap();
        registry.validate_safe_point(handle, safe_point).unwrap();
        assert_eq!(safe_point.code_unit.generation(), handle.generation());
        assert_eq!(safe_point.code_unit.ordinal(), 0);

        let malformed = BlueJsSafePoint {
            code_unit: safe_point.code_unit,
            bytecode_offset: safe_point.bytecode_offset + 1,
        };
        assert_eq!(
            registry.validate_safe_point(handle, malformed),
            Err(BlueJsProgramDebugError::InvalidInstructionBoundary)
        );
    }

    #[test]
    fn nested_function_code_units_are_named_in_preorder() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(
                source("page:///nested.js", "sha256:nested"),
                &script("function answer(){return 42;} answer();"),
            )
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(compiled.code_units().len(), 2);
        assert_eq!(compiled.code_units()[0].id().ordinal(), 0);
        assert_eq!(compiled.code_units()[1].id().ordinal(), 1);
        let nested_safe_point = BlueJsSafePoint {
            code_unit: compiled.code_units()[1].id(),
            bytecode_offset: compiled.code_units()[1].instruction_offsets()[0],
        };
        registry
            .validate_safe_point(handle, nested_safe_point)
            .unwrap();
    }

    #[test]
    fn replacing_or_invalidating_a_program_fails_closed_for_old_ids() {
        let mut registry = BlueJsProgramRegistry::default();
        let first = registry
            .install(source("page:///main.js", "sha256:old"), &script("1"))
            .unwrap();
        let stale_safe_point = registry.get(first).unwrap().safe_points().next().unwrap();
        let stale_ast_node = registry.get(first).unwrap().ast_nodes()[0].id();
        let second = registry
            .replace(first, source("page:///main.js", "sha256:new"), &script("2"))
            .unwrap();
        assert_ne!(first.generation(), second.generation());
        assert!(matches!(
            registry.get(first),
            Err(BlueJsProgramDebugError::UnknownProgram)
        ));
        assert_eq!(
            registry.validate_safe_point(first, stale_safe_point),
            Err(BlueJsProgramDebugError::UnknownProgram)
        );
        assert_eq!(
            registry.validate_safe_point(second, stale_safe_point),
            Err(BlueJsProgramDebugError::StaleSafePoint)
        );
        assert_eq!(
            registry.validate_ast_node(first, stale_ast_node),
            Err(BlueJsProgramDebugError::UnknownProgram)
        );
        assert_eq!(
            registry.validate_ast_node(second, stale_ast_node),
            Err(BlueJsProgramDebugError::StaleAstNode)
        );
        assert!(registry.invalidate(second));
        assert!(!registry.invalidate(second));
    }

    #[test]
    fn failed_replacement_preserves_the_previous_generation() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(source("page:///main.js", "sha256:old"), &script("1"))
            .unwrap();
        let invalid = script("let duplicate; let duplicate;");
        assert!(matches!(
            registry.replace(handle, source("page:///main.js", "sha256:bad"), &invalid),
            Err(BlueJsProgramDebugError::Compilation(
                CompileError::DuplicateBinding(_)
            ))
        ));
        assert_eq!(
            Vm::default()
                .execute(registry.get(handle).unwrap().bytecode())
                .unwrap(),
            Value::Number(1.0)
        );
    }

    #[test]
    fn source_identity_rejects_missing_required_fields() {
        assert_eq!(
            BlueJsSourceIdentity::new("", "sha256:value"),
            Err(BlueJsProgramDebugError::EmptyCanonicalModuleId)
        );
        assert_eq!(
            BlueJsSourceIdentity::new("page:///main.js", ""),
            Err(BlueJsProgramDebugError::EmptySourceHash)
        );
    }

    #[test]
    fn structured_programs_expose_and_validate_executable_ast_nodes() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(
                source("page:///main.js", "sha256:ast"),
                &script("let value=1+2; value;"),
            )
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(compiled.ast_nodes()[0].kind(), BlueJsAstNodeKind::Script);
        assert_eq!(compiled.ast_nodes()[0].id().ordinal(), 0);
        let expression = compiled
            .ast_nodes()
            .iter()
            .find(|node| node.kind() == BlueJsAstNodeKind::Expression)
            .copied()
            .unwrap();
        registry.validate_ast_node(handle, expression.id()).unwrap();
        let statement = compiled
            .ast_nodes()
            .iter()
            .find(|node| node.is_top_level_statement())
            .copied()
            .unwrap();
        let safe_point = registry
            .safe_point_for_ast_node(handle, statement.id())
            .unwrap();
        registry.validate_safe_point(handle, safe_point).unwrap();

        let malformed = BlueJsAstNodeId {
            generation: handle.generation(),
            ordinal: u32::MAX,
        };
        assert_eq!(
            registry.validate_ast_node(handle, malformed),
            Err(BlueJsProgramDebugError::UnknownAstNode)
        );
    }

    #[test]
    fn empty_root_statement_is_explicitly_unbound() {
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install(source("page:///empty.js", "sha256:empty"), &script("; 42;"))
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        let top_level_statements = compiled
            .ast_nodes()
            .iter()
            .filter(|node| node.is_top_level_statement())
            .copied()
            .collect::<Vec<_>>();
        assert_eq!(top_level_statements.len(), 2);
        assert_eq!(
            registry.safe_point_for_ast_node(handle, top_level_statements[0].id()),
            Err(BlueJsProgramDebugError::AstNodeUnbound)
        );
        let safe_point = registry
            .safe_point_for_ast_node(handle, top_level_statements[1].id())
            .unwrap();
        registry.validate_safe_point(handle, safe_point).unwrap();
    }

    #[test]
    fn precompiled_bytecode_uses_the_same_generation_bound_validation() {
        let program = script("40 + 2");
        let bytecode = program.compile().unwrap();
        let mut registry = BlueJsProgramRegistry::default();
        let handle = registry
            .install_precompiled(source("page:///main.js", "sha256:compiled"), bytecode)
            .unwrap();
        let compiled = registry.get(handle).unwrap();
        assert_eq!(
            Vm::default().execute(compiled.bytecode()).unwrap(),
            Value::Number(42.0)
        );
        registry
            .validate_safe_point(handle, compiled.safe_points().next().unwrap())
            .unwrap();
    }
}
